server:
  port: 8082

spring:
  application:
    name: service_b

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    password: password
    username: user
    driver-class-name: org.postgresql.Driver

  cloud:
    openfeign:
      client:
        config:
          service-b:
            connect-timeout: 3000
            read-timeout: 5000

  data:
    redis:
      host: localhost
      port: 6379

app:
  dispatcher:
    delay-ms: 5000

service-c:
  uri: http://localhost:9090