spring:
  profiles:
    active: dev

  application:
    name: service_c

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true

  kafka:
    topic:
      out: event-output-topic
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      enableIdempotence: ${KAFKA_PRODUCER_IDEMPOTENCE}
      acks: ${KAFKA_PRODUCER_ACKS}

  datasource:
    url: ${DATASOURCE_URL}
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  dispatcher:
    delay-ms: 5000