spring:
  application:
    name: service_a

  cloud:
    openfeign:
      client:
        config:
          service-b:
            connect-timeout: 3000
            read-timeout: 5000

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      in: event-input-topic
    bootstrap-servers: localhost:9094
    consumer:
      auto-offset-reset: earliest
      group-id: service-a-v2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mongodb:
    uri: mongodb://localhost:27017/service-a-db
    representation:
      uuid: standard


service-b:
  uri: http://localhost:8082/

server:
  port: 8081